// examples/angular-consumer/src/main.ts
import { bootstrapApplication } from "@angular/platform-browser";
import { Component, CUSTOM_ELEMENTS_SCHEMA, ViewChild } from "@angular/core";
import type { ElementRef } from "@angular/core";
import { FormControl, ReactiveFormsModule } from "@angular/forms";
import {
  registerComplexComponents,
  sampleCustomers
} from "@fahimc/react-web-component-bridge-test-components";

registerComplexComponents();

@Component({
  selector: "app-root",
  standalone: true,
  imports: [ReactiveFormsModule],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <rwcb-customer-picker
      #picker
      ngDefaultControl
      [attr.selected-id]="control.value"
      (customer-select)="selectCustomer($event)"
    ></rwcb-customer-picker>
    <button type="button" (click)="focus()">Focus</button>
  `
})
class AppComponent {
  @ViewChild("picker", { static: true }) picker!: ElementRef<
    HTMLElement & { customers: unknown[]; focusSearch(): void }
  >;
  control = new FormControl("c1", { nonNullable: true });

  ngAfterViewInit(): void {
    this.picker.nativeElement.customers = sampleCustomers().slice(0, 20);
  }

  selectCustomer(event: Event): void {
    const customer = (event as CustomEvent<{ id?: string }>).detail;
    this.control.setValue(customer?.id ?? "");
  }

  focus(): void {
    this.picker.nativeElement.focusSearch();
  }
}

bootstrapApplication(AppComponent);

// examples/react-consumer/src/main.tsx
import React, { useEffect, useRef } from "react";
import { createRoot } from "react-dom/client";
import {
  registerComplexComponents,
  sampleCustomers
} from "@fahimc/react-web-component-bridge-test-components";

registerComplexComponents();

declare module "react" {
  namespace JSX {
    interface IntrinsicElements {
      "rwcb-customer-picker": React.DetailedHTMLProps<
        React.HTMLAttributes<HTMLElement>,
        HTMLElement
      >;
    }
  }
}

function App() {
  const ref = useRef<HTMLElement & { customers: unknown[]; focusSearch(): void }>(null);
  useEffect(() => {
    if (ref.current) {
      ref.current.customers = sampleCustomers().slice(0, 10);
      ref.current.addEventListener("customer-select", (event) =>
        console.log((event as CustomEvent).detail)
      );
    }
  }, []);
  return <rwcb-customer-picker ref={ref} selected-id="c1" />;
}

createRoot(document.getElementById("root")!).render(<App />);
